modLoader="kotori_scala"
loaderVersion="[2.13.3,2.14.0)"
license="All rights reserved"
[[mods]]
modId="kagawaassist"
version="${file.jarVersion}"
displayName="KagawaAssist"
logoFile="KagawaAssist.png"
credits="Thanks for this example mod goes to Java"
authors="Love, Cheese and small house plants"
description='''
香川用mod
'''
side="CLIENT"
[[dependencies.kagawaassist]]
modId="forge"
mandatory=true
versionRange="[39,)"
ordering="NONE"
side="BOTH"
[[dependencies.kagawaassist]]
modId="minecraft"
mandatory=true
versionRange="[1.18.1,1.19)"
ordering="NONE"
side="BOTH"
