modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
[[mods]]
modId="kagawa-assist"
version="${file.jarVersion}"
displayName="KagawaAssist"
logoFile="KagawaAssist.png"
credits="Thanks for this example mod goes to Java"
authors="Love, Cheese and small house plants"
description='''
香川用mod
'''
side="CLIENT"
[[dependencies.kagawa-assist]]
modId="forge"
mandatory=true
versionRange="[39,)"
ordering="NONE"
side="BOTH"
[[dependencies.kagawa-assist]]
modId="minecraft"
mandatory=true
versionRange="[1.18.1,1.19)"
ordering="NONE"
side="BOTH"
